#!/bin/bash
# Creates all the symlink on new PCs.
# Note, the vim config is in a separate repo.

DOTFILES=$PWD
cd ~

function symlink {
    filename=$1
    if [ -e $filename ]; then
        echo "Skipped symlinking $filename, because the file already exists."
    else
        echo "Linking ~/$filename to $DOTFILES/$filename."
        ln -s $DOTFILES/$filename || \
            { echo "'ln -s $DOTFILES/$filename' failed."; exit 1; }
    fi
}

symlink .bashrc
symlink .gitconfig
symlink .git_template
symlink .astylerc
symlink .reviewboardrc
symlink .latexmkrc
symlink .ycm_extra_conf

echo "Should the aliases be added to your .bashrc? (yes/no)"
read ANSWER
if [ "$ANSWER" = "yes" ]; then
    echo "source $DOTFILES/aliases" >> .bashrc
    echo "aliases have been added."
fi

