#!/bin/bash
# Creates all the symlink on new PCs.
# Note, the vim config is in a separate repo.

DOTFILES=$PWD
cd ~
[ -e .gitconfig ] || ln -s $DOTFILES/.gitconfig
[ -e .git_template ] || ln -s $DOTFILES/.git_template
[ -e .astylerc ] || ln -s $DOTFILES/.astylerc
[ -e .reviewboardrc ] || ln -s $DOTFILES/.reviewboardrc
[ -e .latexmkrc ] || ln -s $DOTFILES/.latexmkrc

echo "Should the alieses be added to your .bashrc? (yes/no)"
read ANSWER
if [ "$ANSWER" = "yes" ]; then
    echo "source $DOTFILES/aliases" >> .bashrc
    echo "aliases have been added."
fi

