#!/bin/bash
################################################################################
# tmuxgo - Dale Bewley <dale @ guifreelife org> - Sat Feb 19 08:53:30 PST 2011
#-------------------------------------------------------------------------------
# Use me to get your tmux session restored after a reboot or reattach daily.
# Just type tmuxgo every morning and hit ^bd at the end of the day. Login
# remotely and do the same.
#
# Attaches to an existing session named $SESSION or will create one if missing.
# The created session will be pre-populated with a number of windows.
#
# For example, window 0 running IRC, window 1 running email, window 2 logged
# into a router used daily.
#
#
# Bugs & Todos:
#   o If session already exists, instantiate any missing windows.
#     This could be done by checking tmux list-windows, not sure needed.
#
#   o Window 0 automatically changes name to 'weechat 0.3.3', ignoring
#     the -n option. The following should fix it, but does not:
#       tmux set-window-option -t $SESSION:0 automatic-rename off
#     Same thing happens when issuing configure command on Arista switches.
#     Note that name (#W) and title (#T) are not necessarily the same value.
################################################################################

# the name of your primary tmux session
SESSION=$USER
# your IRC nickname
IRC_NICK=$USER

# if the session is already running, just attach to it.
tmux has-session -t $SESSION
if [ $? -eq 0 ]; then
    echo "Session $SESSION already exists. Attaching."
    sleep 1
    tmux -2 attach -t $SESSION
    exit 0;
fi

# create a new session, named $SESSION, and detach from it
tmux new-session -d -s $SESSION

# Now populate the session with the windows you use every day
# Some windows I specifically want at a particular index.
# I always want IRC in window 0 and Email in window 1.

# weechat - IRC
tmux new-window    -t $SESSION:0 -k -n irc weechat
#tmux set-window-option -t $SESSION:0 monitor-activity on
#tmux set-window-option -t $SESSION:0 visual-activity on
#tmux select-pane -t $SESSION:0.0
#tmux set-window-option -t $SESSION:0 automatic-rename off

# mail
tmux new-window    -t $SESSION:1 -k -n mail mutt
tmux set-window-option -t $SESSION:1 automatic-rename off
tmux split-window -h -l 80 -t $SESSION:1 calcurse
# calcurse cause activity all the time
tmux set-window-option -t $SESSION:1 monitor-activity off
tmux select-pane -L

# work
tmux new-window    -t $SESSION:2 -k -n work "cd ~/work; bash"
tmux set-window-option -t $SESSION:2 automatic-rename off

# compile
tmux new-window    -t $SESSION:3 -k -n compile "cd ~/work; bash"
tmux set-window-option -t $SESSION:4 monitor-silence 5
tmux set-window-option -t $SESSION:4 automatic-rename off

# debug
tmux new-window    -t $SESSION:4 -k -n debug "cd ~/work; bash"
tmux set-window-option -t $SESSION:3 automatic-rename off

# offlineimap
tmux new-window    -t $SESSION:8 -k -n imap offlineimap

# music
tmux new-window    -t $SESSION:9 -k -n music "cmus"
tmux set-window-option -t $SESSION:9 automatic-rename off

# all done. select starting window and get to work
# you may need to cycle through windows and type in passwords
# if you don't use ssh keys
tmux select-window -t $SESSION:0
tmux -2 attach -t $SESSION


